name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.1.0
  geolocator: ^7.6.2
  http: ^0.13.3

#  cupertino_icons: ^1.0.3
#  geolocator: ^7.6.2
#  http: ^0.13.3
#  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - images/

  fonts:
    - family: Spartan
      fonts:
        - asset: fonts/Spartan-Black.otf
          weight: 900
        - asset: fonts/Spartan-Regular.ttf
          style: normal